name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [18.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: npm install

      - name: build
        run: npm run make

      # - name: Make ready to upload
      #   run: |
      #          cd out/make
      #          zip -r dist.zip .
      #          cd ../..
      #          mv out/make/dist.zip .
      #   shell: bash
      #
      #
      # - name: Upload to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: "dist.zip"
      #     asset_name: "dist-${{ matrix-os }}-node${{ matrix.node-version }}.zip"
      #     tag: output-${{ github.ref }}
      #     overwrite: true

      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
