name: Build

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [18.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: npm install

      - name: build
        run: npm run make

      - name: Make ready to upload
        run: |
          mkdir -p uploads
          find out/make -type f -exec mv {} uploads/ \;
        shell: bash

      - name: Set Release Tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_NAME="${GITHUB_REF##*/}"  # Extract tag name
          else
            TAG_NAME="output-${GITHUB_REF##*/}"
          fi
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        shell: bash

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "uploads/*"
          tag: "${{ env.TAG_NAME }}"
          overwrite: true
          file_glob: true
